name: C-github-actions

on: [push]

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: install header libraries
                          run: sudo apt-get install libpam0g-dev
                        - name: make
                          run: make
